before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/cider
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - openbsd
      - windows
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=cidertool

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: '{{ .Tag }}-next'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
      - go mod tidy

dockers:
  - dockerfile: build/Dockerfile
    image_templates:
      - cidertool/cider:{{ .Tag }}
      - cidertool/cider:v{{ .Major }}
      - cidertool/cider:v{{ .Major }}.{{ .Minor }}
      - cidertool/cider:latest
    ids:
      - cider
    extra_files:
      - build/entrypoint.sh
    build_flag_templates:
      - --pull
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.name={{ .ProjectName }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.source={{ .GitURL }}
      - --label=repository=http://github.com/cidertool/cider
      - --label=homepage=http://cidertool.github.io/cider
      - --label=maintainer=Aaron Sky <cider@skyaaron.com>

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

brews:
  - name: cider
    description: Submit your builds to the Apple App Store in seconds
    homepage: https://cidertool.github.io/cider
    tap:
      owner: cidertool
      name: homebrew-tap
    folder: Formula
    commit_author:
      name: cider-bot
      email: cider@skyaaron.com
    test: |
      system "#{bin}/cider", "-v"
#  - name: cider-core
#    description: Submit your builds to the Apple App Store in seconds
#    homepage: https://cidertool.github.io/cider
#    tap:
#      owner: cidertool
#      name: homebrew-tap
#    folder: Formula
#    commit_author:
#      name: cider-bot
#      email: cider@skyaaron.com
#    dependencies:
#      - name: go
#        type: build
#    install: |
#      system "go", "build", "-ldflags",
#              "-s -w -X main.version=#{version} -X main.commit=#{stable.specs[:revision]} -X main.builtBy=homebrew",
#              *std_go_args
#      man1.install "docs/man/cider.1"
#      man1.install "docs/man/cider_init.1"
#      man1.install "docs/man/cider_release.1"
#      man1.install "docs/man/cider_check.1"
#      man1.install "docs/man/cider_completions.1"
#    test: |
#      system "#{bin}/cider", "-v"

scoop:
  description: Submit your builds to the Apple App Store in seconds
  homepage: https://cidertool.github.io/cider
  license: GPL-3.0-or-later
  bucket:
    owner: cidertool
    name: scoop-bucket
  commit_author:
    name: cider-bot
    email: cider@skyaaron.com
