before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - openbsd
      - windows
    goarch:
      - amd64
      - arm64
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.builtBy=cidertool
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: '{{ .Tag }}-next'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
      - go mod tidy
dockers:
  - dockerfile: docker/Dockerfile
    image_templates:
      - cidertool/cider:{{ .Tag }}
      - cidertool/cider:v{{ .Major }}
      - cidertool/cider:v{{ .Major }}.{{ .Minor }}
      - cidertool/cider:latest
    binaries:
      - cider
    extra_files:
      - docker/entrypoint.sh
    build_flag_templates:
      - --pull
      - --label=org.opencontainers.image.created={{ .Date }}
      - --label=org.opencontainers.image.name={{ .ProjectName }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.source={{ .GitURL }}
      - --label=repository=http://github.com/cidertool/cider
      - --label=homepage=http://cidertool.github.io/cider
      - --label=maintainer=Aaron Sky <cider@skyaaron.com>
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
brews:
  - tap:
      owner: cidertool
      name: homebrew-tap
    commit_author:
      name: cider-bot
      email: cider@skyaaron.com
    folder: Formula
    homepage: https://cidertool.github.io/cider
    description: Submit your builds to the Apple App Store in seconds
    test: |
      system "#{bin}/cider -v"
scoop:
  bucket:
    owner: cidertool
    name: scoop-bucket
  commit_author:
    name: cider-bot
    email: cider@skyaaron.com
  homepage: https://cidertool.github.io/cider
  description: Submit your builds to the Apple App Store in seconds
  license: MIT
