title: Applereleaser
# description: Applereleaser documentation
# url: https://aaronsky.github.io/applereleaser
# permalink: pretty
remote_theme: pmarsceill/just-the-docs
# logo: "/assets/images/just-the-docs.png"
# color_scheme: dark
search_enabled: false

# plugins:
#   - jekyll-seo-tag

# heading_anchors: true
# aux_links:
#   GitHub:
#     - '//github.com/aaronsky/applereleaser'
# aux_links_new_tab: true

# footer_content: 'Copyright &copy; 2020 Aaron Sky. Distributed under the <a href="https://github.com/aaronsky/applereleaser/blob/main/LICENSE">MIT license</a>.'
# # last_edit_timestamp show or hide edit time - page must have `last_modified_date` defined in the frontmatter
# last_edit_timestamp: true
# # last_edit_time_format uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
# last_edit_time_format: '%b %e %Y at %I:%M %p'
